// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTkFLFtR1FWoxHppVJ3JHFt7YuT3AbWg4',
    appId: '1:719956929559:web:30da5086993eb6d7654052',
    messagingSenderId: '719956929559',
    projectId: 'shubhride-9b16d',
    authDomain: 'shubhride-9b16d.firebaseapp.com',
    storageBucket: 'shubhride-9b16d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXYeYas0d6RcJrf2hTglxlBpwoHF8Y4w0',
    appId: '1:719956929559:android:f14c71015c25d39d654052',
    messagingSenderId: '719956929559',
    projectId: 'shubhride-9b16d',
    storageBucket: 'shubhride-9b16d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIsfGFo4qJlGzr-KViFWNZd9yp4LafS98',
    appId: '1:719956929559:ios:bcb6d064444de139654052',
    messagingSenderId: '719956929559',
    projectId: 'shubhride-9b16d',
    storageBucket: 'shubhride-9b16d.firebasestorage.app',
    iosBundleId: 'com.riderpay.riderPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIsfGFo4qJlGzr-KViFWNZd9yp4LafS98',
    appId: '1:719956929559:ios:bcb6d064444de139654052',
    messagingSenderId: '719956929559',
    projectId: 'shubhride-9b16d',
    storageBucket: 'shubhride-9b16d.firebasestorage.app',
    iosBundleId: 'com.riderpay.riderPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTkFLFtR1FWoxHppVJ3JHFt7YuT3AbWg4',
    appId: '1:719956929559:web:63bd4704f56a1dde654052',
    messagingSenderId: '719956929559',
    projectId: 'shubhride-9b16d',
    authDomain: 'shubhride-9b16d.firebaseapp.com',
    storageBucket: 'shubhride-9b16d.firebasestorage.app',
  );

}